# This is a basic workflow to help you get started with Actions

name: 手动触发构建镜像到docker仓库和GHCR仓库

# Controls when the action will run. 
on:
  # 任意推送都会触发构建
  #push:
# 定时调度
  #schedule:
    #- cron: "0 0 * * 1"

  # Allows you to run this workflow manually from the Actions tab
# 可以手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'   
        required: true
        default: 'warning'
      tags:
        description: 'tags：请填写镜像版本号'
        required: true
        default: ''


jobs:
  buildx:
    runs-on: ubuntu-latest
    
    # 这里用于定义 GITHUB_TOKEN 的权限
    permissions:
       packages: write
       contents: read
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: image Name change
        id: read-docker-image-identifiers
        run: |
          echo DOCKER_IMAGENAME=$(echo ${{ secrets.DOCKER_IMAGENAME }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGENAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGENAME }}
        # generate Docker tags based on the following events/attributes
        # metadata 使用说明：https://github.com/docker/metadata-action
        #   latest, tags
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.event.inputs.tags }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .	# 工作目录
          file: ./Dockerfile	#构建文件路径
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
# 镜像推送
          push: true
# 给清单打上多个tags标签  
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}